version: "3"
services:
  mongo:
    image: mongo:3.6
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/line_todo
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
